### ISSUE TITLE
Allow partial match for ownership identifier

### ISSUE THREAD

**Issue by leinardi** [spotify/ruler#48]
### Feature description

It would be really convenient to be able to use a partial match of the identifier inside the `ownership.yaml`.

For example, I would expect this `ownership.yaml`:
```yaml
- identifier: :modules:core
  owner: core

- identifier: :modules:feature
  owner: feature

- identifier: androidx
  owner: androidx

- identifier: com.google
  owner: google
```
to match all the dependencies that start with the group `androidx` to the owner androidx like, for example `androidx.compose.ui:ui` and `androidx.core:core`, and all the module that start with `:modules:core` to the owner core:
![image](https://user-images.githubusercontent.com/273338/154155546-f71ca708-1b66-44df-af46-86f08ac16e39.png)

### Reasoning

Keeping track of all the AndroidX and Google library would require too much effort and would be prone to error. It would be way better to be able to a partial matching to quickly group together these kind of libraries.
It would be also nice to use a similar logic for the gradle modules.
